"""add some_at to fisheries

Revision ID: 9b41c5072d9e
Revises: d3c77d5456e4
Create Date: 2025-07-31 01:43:03.740783

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b41c5072d9e"
down_revision: Union[str, Sequence[str], None] = "d3c77d5456e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fisheries",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "fisheries",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "fisheries",
        "embedding",
        existing_type=Vector(dim=384),
        type_=Vector(dim=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fisheries",
        "embedding",
        existing_type=Vector(dim=1024),
        type_=Vector(dim=384),
        existing_nullable=False,
    )
    op.drop_column("fisheries", "updated_at")
    op.drop_column("fisheries", "created_at")
    # ### end Alembic commands ###
