"""initial migration

Revision ID: d3c77d5456e4
Revises:
Create Date: 2025-07-31 01:21:42.413576

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3c77d5456e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fisheries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_name", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("embedding", Vector(dim=384), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fisheries")
    # ### end Alembic commands ###
